Database:
  cockroach:
    host: systemd-zitadel-db
    port: 26257
    database: zitadel
    user:
      username: zitadel
      ssl:
        mode: disable
    admin:
      username: root
      ssl:
        mode: disable