FROM docker.io/frappe/erpnext:v16

WORKDIR /home/frappe/frappe-bench

RUN bench get-app --branch version-16 --skip-assets https://github.com/frappe/hrms \
    && bench get-app --branch main --skip-assets https://github.com/frappe/helpdesk \
    && bench get-app --branch main --skip-assets https://github.com/frappe/crm \
    && bench get-app --branch master --skip-assets https://github.com/frappe/builder \
    && bench get-app --branch master --skip-assets https://github.com/frappe/wiki \
    && bench get-app --branch main --skip-assets https://github.com/frappe/insights \
    && bench get-app --branch main --skip-assets https://github.com/frappe/lms \
    && bench build --production