FROM docker.io/frappe/erpnext:v16

WORKDIR /home/frappe/frappe-bench

RUN bench get-app --branch version-16 --skip-assets https://github.com/frappe/hrms \
    && bench get-app --branch version-16 --skip-assets https://github.com/frappe/payments \
    && bench get-app --branch develop --skip-assets https://github.com/frappe/telephony \
    && bench get-app --branch main --skip-assets https://github.com/frappe/helpdesk \
    && bench get-app --branch main --skip-assets https://github.com/frappe/crm \
    && bench get-app --branch master --skip-assets https://github.com/frappe/builder \
    && bench get-app --branch master --skip-assets https://github.com/frappe/wiki \
    && bench get-app --branch main --skip-assets https://github.com/frappe/insights \
    && bench get-app --branch main --skip-assets https://github.com/frappe/lms \
    && echo '{"socketio_port": 9000}' > sites/common_site_config.json \
    && bench build --production \
    && rm sites/common_site_config.json \
    && bench setup nginx --yes 2>/dev/null || true \
    && for link in sites/assets/*/; do \
         if [ -L "${link%/}" ]; then \
           real=$(readlink -f "${link%/}"); \
           rm "${link%/}"; \
           cp -r "$real" "${link%/}"; \
         fi; \
       done