FROM docker.io/frappe/erpnext:v16

WORKDIR /home/frappe/frappe-bench

RUN bench get-app --branch version-16 --skip-assets https://github.com/frappe/hrms \
    && bench get-app --branch main --skip-assets https://github.com/frappe/helpdesk \
    && bench get-app --branch main --skip-assets https://github.com/frappe/crm \
    && bench get-app --branch master --skip-assets https://github.com/frappe/builder \
    && bench get-app --branch master --skip-assets https://github.com/frappe/wiki \
    && bench get-app --branch main --skip-assets https://github.com/frappe/insights \
    && bench get-app --branch main --skip-assets https://github.com/frappe/lms \
    && echo '{"socketio_port": 9000}' > sites/common_site_config.json \
    && bench build --production \
    && rm sites/common_site_config.json \
    && mkdir -p sites/assets \
    && bench setup nginx --yes 2>/dev/null || true \
    && cp -rT apps/frappe/frappe/public sites/assets/frappe \
    && cp -rT apps/erpnext/erpnext/public sites/assets/erpnext \
    && cp -rT apps/hrms/hrms/public sites/assets/hrms \
    && cp -rT apps/wiki/wiki/public sites/assets/wiki \
    && cp -rT apps/lms/lms/public sites/assets/lms